$('.pass-list').click(function()
{
    $.ajax({
        url:"../controls/controlerFichar.php",
        type:'POST',
        data:'asd',
        success:function()
        {
           console.log("Success");
        }
    });
}
);